[package]
name = "know_ball"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rusqlite = { version = "0.31", features = ["bundled"] }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"